In [1]:
import pandas as pd

# Uploading dataset

In [2]:
train = pd.read_parquet("/content/train-00000-of-00001.parquet")
test = pd.read_parquet("/content/test-00000-of-00001.parquet")
validation = pd.read_parquet("/content/validation-00000-of-00001.parquet")

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67349 entries, 0 to 67348
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   idx       67349 non-null  int32
 1   sentence  67349 non-null  object
 2   label     67349 non-null  int64
dtypes: int32(1), int64(1), object(1)
memory usage: 1.3+ MB

In [6]:
train.shape

(67349, 3)

In [7]:
validation.shape

(872, 3)

In [8]:
print("Information about train dataset")
print(train.info())

Information about train dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67349 entries, 0 to 67348
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   idx       67349 non-null  int32
 1   sentence  67349 non-null  object
 2   label     67349 non-null  int64
dtypes: int32(1), int64(1), object(1)
memory usage: 1.3+ MB
None

In [9]:
print("Information about validation dataset")
print(validation.info())

Information about validation dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 872 entries, 0 to 871
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   idx       872 non-null    int32
 1   sentence  872 non-null    object
 2   label     872 non-null    int64
dtypes: int32(1), int64(1), object(1)
memory usage: 17.2+ KB
None

In [12]:
train.head(5)

   idx                                           sentence  label
0    0       hide new secretions from the parental units       0
1    1               contains no wit , only labored gags       0
2    2  that loves its characters and communicates som...      1
3    3  remains utterly satisfied to remain the same t...      0
4    4  on the worst revenge-of-the-nerds clichés the ...      0

In [13]:
train_text = train["sentence"]
train_label = train["label"]

val_text = validation["sentence"]
val_label = validation["label"]

In [14]:
from numpy import vectorize
from sklearn.feature_extraction.text import TfidfVectorizer

vectorize = TfidfVectorizer(stop_words="english", max_df=0.7)

train_vectors = vectorize.fit_transform(train_text)
val_vectors = vectorize.transform(val_text)

In [15]:
import numpy as np

positive_vector = train_vectors[np.array(train_label) == 1].mean(axis=0)
negative_vector = train_vectors[np.array(train_label) == 0].mean(axis=0)

In [16]:
positive_vector = np.asarray(positive_vector)
negative_vector = np.asarray(negative_vector)

In [17]:
print(train_vectors.shape)
print(val_vectors.shape)
print(positive_vector.shape)
print(negative_vector.shape)

(67349, 13491)
(872, 13491)
(1, 13491)
(1, 13491)

# TF-IDF + Cosine Similarity

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

positive_similarity = cosine_similarity(val_vectors, positive_vector)
negative_similarity = cosine_similarity(val_vectors, negative_vector)

In [19]:
predictions_cos = (positive_similarity > negative_similarity).astype(int)

In [20]:
from sklearn.metrics import accuracy_score, f1_score

f1_cos = f1_score(val_label, predictions_cos)

accuracy_cos = accuracy_score(val_label, predictions_cos)

print("TF-IDF + Cosine Similarity Results")
print("Accuracy:", accuracy_cos)
print("F1:", f1_cos)

TF-IDF + Cosine Similarity Results
Accuracy: 0.7477064220183486
F1: 0.7544642857142857

In [21]:
from sklearn.metrics import classification_report
print("TF-IDF + Cosine Similarity Results")
print(classification_report(val_label, predictions_cos, target_names=["Negative", "Positive"]))

TF-IDF + Cosine Similarity Results
              precision    recall  f1-score   support

    Negative       0.75      0.73      0.74       428
    Positive       0.75      0.76      0.75       444

    accuracy                           0.75       872
   macro avg       0.75      0.75      0.75       872
weighted avg       0.75      0.75      0.75       872

# TF-IDF + Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()
logReg.fit(train_vectors, train_label)

LogisticRegression()

In [23]:
predictions_logReg = logReg.predict(val_vectors)

In [24]:
f1_logReg = f1_score(val_label, predictions_logReg)

accuracy_logReg = accuracy_score(val_label, predictions_logReg)

print("TF-IDF + Logistic Regression Results")
print("Accuracy:", accuracy_logReg)
print("F1:", f1_logReg)

TF-IDF + Logistic Regression Results
Accuracy: 0.8038990825688074
F1: 0.8209424083769633

In [25]:
print("TF-IDF + Logistic Regression Results")
print(classification_report(val_label, predictions_logReg, target_names=["Negative", "Positive"]))

TF-IDF + Logistic Regression Results
              precision    recall  f1-score   support

    Negative       0.86      0.72      0.78       428
    Positive       0.77      0.88      0.82       444

    accuracy                           0.80       872
   macro avg       0.81      0.80      0.80       872
weighted avg       0.81      0.80      0.80       872

# TF-IDF + Support Vector Machine

In [27]:
from sklearn.svm import SVC

In [ ]:
svm = SVC()
svm.fit(train_vectors, train_label)

In [ ]:
predictions_svm = svm.predict(val_vectors)

In [ ]:
f1_svm = f1_score(val_label, predictions_svm)

accuracy_svm = accuracy_score(val_label, predictions_svm)
print("TF-IDF + Support Vector Machine Results")
print("Accuracy:", accuracy_svm)
print("F1:", f1_svm)

TF-IDF + Support Vector Machine Results
Accuracy: 0.7993119266055045
F1: 0.8175182481751825

In [ ]:
print("TF-IDF + Support Vector Machine Results")
print(classification_report(val_label, predictions_svm, target_names=["Negative", "Positive"]))

# BERT

In [4]:
from datasets import Dataset
train_dataset = Dataset.from_pandas(train)
val_dataset = Dataset.from_pandas(validation)

In [5]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [6]:
def tokenize_function(dataset):
    return tokenizer(
        dataset["sentence"],
        truncation=True,
        padding="max_length",
        max_length=128)

In [7]:
train_tokenized = train_dataset.map(tokenize_function)
val_tokenized = val_dataset.map(tokenize_function)

Map:   0%|          | 0/67349 [00:00<?, ? examples/s]

Map:   0%|          | 0/872 [00:00<?, ? examples/s]

In [8]:
print(train_tokenized.column_names)

['idx', 'sentence', 'label', 'input_ids', 'token_type_ids', 'attention_mask']

In [10]:
train_tokenized.data

InMemoryTable
idx: int32
sentence: string
label: int64
input_ids: list<item: int32>
  child 0, item: int32
token_type_ids: list<item: int8>
  child 0, item: int8
attention_mask: list<item: int8>
  child 0, item: int8
----
idx: [[0,1,2,3,4,...,995,996,997,998,999],[1000,1001,1002,1003,1004,...,1995,1996,1997,1998,1999],...,[66000,66001,66002,66003,66004,...,66995,66996,66997,66998,66999],[67000,67001,67002,67003,67004,...,67344,67345,67346,67347,67348]]
sentence: [["hide new secretions from the parental units ","contains no wit , only labored gags ","that loves its characters and communicates something rather beautiful about human nature ","remains utterly satisfied to remain the same throughout ","on the worst revenge-of-the-nerds clichés the filmmakers could dredge up ",...,"you wish you were at home watching that movie instead of in the theater watching this one ","'s no point in extracting the bare bones of byatt 's plot for purposes of bland hollywood romance ","underdeveloped ","the jokes are flat ","a heartening tale of small victories "],["suspense , intriguing characters and bizarre bank robberies , ","a gritty police thriller with all the dysfunctional family dynamics one could wish for ","with a wonderful ensemble cast of characters that bring the routine day to day struggles of the wo (... 20 chars omitted)","nonetheless appreciates the art and reveals a music scene that transcends culture and race . ","do we really need the tiger beat version ? ",...,"when there 's nothing else happening ","on cable ","it with ring , ","far from a groundbreaking endeavor ","that these women are spectacular "],...,["it does turn out to be a bit of a cheat in the end ","may be convinced that he has something significant to say ","to be both hugely entertaining and uplifting . ",", boredom never takes hold . ","left to work with , sort of like michael jackson 's nose ",...,"from a severe case of hollywood-itis ","the very best of them ","thrills , ","'s attracting audiences to unfaithful ","impressively delicate range "],["starts off promisingly but then proceeds to flop ","distinguished actor ","on their parents ' anguish ","pays off and is effective if you stick with it ","is n't particularly funny ",...,"a delightful comedy ","anguish , anger and frustration ","at achieving the modest , crowd-pleasing goals it sets for itself ","a patient viewer ","this new jangle of noise , mayhem and stupidity must be a serious contender for the title . "]]
label: [[0,0,1,0,0,...,0,0,0,0,1],[1,1,1,1,0,...,0,0,1,0,1],...,[0,0,1,1,0,...,0,1,1,1,1],[0,1,0,1,0,...,1,0,1,1,0]]
input_ids: [[[101,5342,2047,3595,8496,...,0,0,0,0,0],[101,3397,2053,15966,1010,...,0,0,0,0,0],...,[101,1996,13198,2024,4257,...,0,0,0,0,0],[101,1037,2540,7406,6925,...,0,0,0,0,0]],[[101,23873,1010,23824,3494,...,0,0,0,0,0],[101,1037,24842,3723,2610,...,0,0,0,0,0],...,[101,2521,2013,1037,23222,...,0,0,0,0,0],[101,2008,2122,2308,2024,...,0,0,0,0,0]],...,[[101,2009,2515,2735,2041,...,0,0,0,0,0],[101,2089,2022,6427,2008,...,0,0,0,0,0],...,[101,1005,1055,15411,9501,...,0,0,0,0,0],[101,8052,2135,10059,2846,...,0,0,0,0,0]],[[101,4627,2125,10015,2135,...,0,0,0,0,0],[101,5182,3364,102,0,...,0,0,0,0,0],...,[101,1037,5776,13972,102,...,0,0,0,0,0],[101,2023,2047,23769,2571,...,0,0,0,0,0]]]
token_type_ids: [[[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0],...,[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0]],[[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0],...,[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0]],...,[[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0],...,[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0]],[[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0],...,[0,0,0,0,0,...,0,0,0,0,0],[0,0,0,0,0,...,0,0,0,0,0]]]
attention_mask: [[[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,1,...,0,0,0,0,0],...,[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,1,...,0,0,0,0,0]],[[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,1,...,0,0,0,0,0],...,[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,1,...,0,0,0,0,0]],...,[[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,1,...,0,0,0,0,0],...,[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,1,...,0,0,0,0,0]],[[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,0,...,0,0,0,0,0],...,[1,1,1,1,1,...,0,0,0,0,0],[1,1,1,1,1,...,0,0,0,0,0]]]

In [11]:
train_tokenized = train_tokenized.remove_columns(["idx", "sentence"])
val_tokenized = val_tokenized.remove_columns(["idx", "sentence"])

In [12]:
print(train_tokenized.column_names)

['label', 'input_ids', 'token_type_ids', 'attention_mask']

In [13]:
from transformers import AutoModelForSequenceClassification
bert = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [15]:
train_dataset

Dataset({
    features: ['idx', 'sentence', 'label'],
    num_rows: 67349
})

In [16]:
val_dataset

Dataset({
    features: ['idx', 'sentence', 'label'],
    num_rows: 872
})

In [17]:
train_tokenized

Dataset({
    features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 67349
})

In [21]:
val_tokenized

Dataset({
    features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 872
})

In [22]:
bert

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [23]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score
def compute_metrics(eval_pred):
    prediction_bert, labels = eval_pred
    prediction_bert = np.argmax(prediction_bert, axis=1)
    return {
        "accuracy": accuracy_score(labels, prediction_bert),
        "f1": f1_score(labels, prediction_bert)
    }

In [24]:
from transformers import TrainingArguments
training_argument = TrainingArguments(
    output_dir = "./bert_sst2",
    num_train_epochs = 2,
    learning_rate = 2e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    eval_strategy = "epoch",
    save_strategy = "no",
    report_to = "none")

In [25]:
from transformers import Trainer
trainer = Trainer(
    model = bert,
    args = training_argument,
    train_dataset = train_tokenized,
    eval_dataset = val_tokenized,
    compute_metrics = compute_metrics)

In [ ]:
trainer.train()